---
abstract: 'Alternate Interface To libmecab'
author:
  - '-2011 Daisuke Maki <daisuke@endeworks.jp>'
build_requires:
  Devel::CheckLib: 0
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.84
  Test::Requires: 0
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  ExtUtils::ParseXS: 2.21
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-MeCab
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Accessor::Fast: 0
  Encode: 0
  Exporter: 0
  File::Spec: 0
  XSLoader: 0.02
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/lestrrat/Text-MeCab.git
version: 0.20016
