--- #YAML:1.0
name:                Text-MeCab
version:             0.20002
abstract:            Alternative Interface To libmecab
license:             ~
author:              
    - Daisuke Maki <daisuke@endeworks.jp>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Accessor::Fast:         0
    Encode:                        0
    Exporter:                      0
    File::Spec:                    0
    Path::Class:                   0
    Test::More:                    0
    Text::CSV_XS:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
